-- Add impersonation audit types to ActionType enum
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'IMPERSONATION_INICIADA';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'IMPERSONATION_FINALIZADA';
